packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - unrs-resolver
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - argon2
  - esbuild
  - nestjs-pino
  - sharp
